package com.burningstack.exoexplorer.utils

enum class FragmentTags(val value: String) {
    PLANET_LIST_FRAGMENT("PLANET_LIST_FRAGMENT"),
    FAVORITES_FRAGMENT("FAVORITES_FRAGMENT"),
    SETTINGS_FRAGMENT("SETTINGS_FRAGMENT"),
    PLANET_DETAILS_FRAGMENT("PLANET_DETAILS_FRAGMENT")
}